version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --reload
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/webapp
      - static:/webapp/static
      - media:/webapp/media
    expose:
      - 8000
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app=config worker --loglevel=info
    volumes:
      - .:/webapp
    environment:
      - CELERY_BROKER=${REDIS}
      - CELERY_BACKEND=${REDIS}
    depends_on:
      - web

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat -l info
    volumes:
      - .:/webapp
    environment:
      - CELERY_BROKER=${REDIS}
      - CELERY_BACKEND=${REDIS}
    depends_on:
      - web

  redis:
    image: redis:7-alpine
    depends_on:
      - db

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery flower -A config --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER=${REDIS}
      - CELERY_BACKEND=${REDIS}
    depends_on:
      - celery

  db:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    volumes:
      - static:/webapp/static
      - media:/webapp/media
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media: