# Generated by Django 4.1.6 on 2023-02-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-modified']},
        ),
    ]
